// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeujzbsvuvqgwjykmqwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldWp6YnN2dXZxZ3dqeWttcXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNDg5OTcsImV4cCI6MjA0ODcyNDk5N30.vfv4I7U0E2d6m9dmFD7oVOsfk9N7z0dSKPrJX4q_xVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);